/**
 * M1 政策规则库种子数据（共享模块）
 * 覆盖 2026年6月四方同责专项治理 8 类问题 + AI魔改管理提示 + 备案形式要件。
 */
import type { InsertRule } from "@db/schema";

export const RULE_SEED_VERSION = "2026.09-v1";

const POLICY_202606 = "广电总局有害低俗与侵权盗版专项治理部署";
const POLICY_202604 = "微短剧备案强制化规定（2026年4月）";
const POLICY_202412 = "管理提示（AI魔改）（2024年12月）";

export const seedRules: InsertRule[] = [
  // ============ 1. 涉儿童有害（阻断级） ============
  {
    ruleCode: "R1-2026-001",
    version: "1.0.0",
    category: "child_harm",
    name: "未成年人受侵害情节",
    severity: "block",
    sourcePolicy: POLICY_202606,
    sourceClause: "8类问题之一：涉儿童有害",
    originalText: "聚焦涉儿童有害等8类问题，制作、投流、推广、播出四方均须审核把关",
    sourceConfidence: "official_text",
    scope: ["full_text"],
    keywords: ["虐待儿童", "猥亵", "童工", "校园霸凌", "诱拐", "拐骗儿童"],
    patterns: ["未成年.{0,12}(侵害|虐待|体罚|殴打)", "(儿童|孩子|小学生).{0,10}(脱|裸|虐)"],
    cooccurrence: [],
    baseConfidence: "0.92",
    remediationTemplate:
      "命中涉儿童有害红线（依据：2026年6月专项治理8类问题之一）。涉及未成年人受侵害情节属阻断级风险，建议删除或彻底改写该情节，不得以任何形式呈现未成年人受害画面细节。",
    platformOverrides: { hongguo: { severity: "block", note: "平台口径加码，零容忍" } },
  },
  {
    ruleCode: "R1-2026-002",
    version: "1.0.0",
    category: "child_harm",
    name: "未成年人成人化演绎",
    severity: "high",
    sourcePolicy: POLICY_202606,
    sourceClause: "8类问题之一：涉儿童有害",
    originalText: "聚焦涉儿童有害等8类问题",
    sourceConfidence: "official_text",
    scope: ["full_text"],
    keywords: ["童星恋爱", "未成年新娘", "童养媳", "儿童模特选秀"],
    patterns: ["(未成年|14岁|15岁|16岁|小学生|初中生).{0,15}(恋爱|结婚|嫁|吻|暧昧)"],
    cooccurrence: [],
    baseConfidence: "0.85",
    remediationTemplate:
      "命中未成年人成人化情节（依据：2026年6月专项治理8类问题之一）。建议移除未成年人恋爱/婚嫁向情节，或将角色明确设定为成年人并在剧本中明示。",
    platformOverrides: {},
  },
  // ============ 2. 软色情擦边 ============
  {
    ruleCode: "R2-2026-001",
    version: "1.0.0",
    category: "soft_porn",
    name: "性暗示与擦边描写",
    severity: "high",
    sourcePolicy: POLICY_202606,
    sourceClause: "8类问题之二：软色情擦边",
    originalText: "聚焦软色情擦边等8类问题",
    sourceConfidence: "official_text",
    scope: ["dialogue", "narration", "full_text"],
    keywords: ["床戏", "一夜情", "陪睡", "潜规则", "脱衣", "欲火", "缠绵", "宽衣解带"],
    patterns: ["(胸部|大腿|身材|曲线).{0,10}(特写|晃动|暴露|若隐若现)", "(喘息|呻吟).{0,8}(娇媚|暧昧|动情)"],
    cooccurrence: [
      { groupA: ["酒店", "卧室", "床"], groupB: ["孤男寡女", "共处一室", "衣衫不整"], window: 60 },
    ],
    baseConfidence: "0.80",
    remediationTemplate:
      "命中软色情擦边判定（依据：专项治理8类问题之二）。建议删除身体部位特写与性暗示描写，改为情节推进型表达；亲密情节以留白或转场处理。",
    platformOverrides: {
      hongguo: { severity: "block", note: "红果4月起审核口径加码，擦边内容直接驳回" },
    },
  },
  {
    ruleCode: "R2-2026-002",
    version: "1.0.0",
    category: "soft_porn",
    name: "擦边职业/场景设定",
    severity: "notice",
    sourcePolicy: POLICY_202606,
    sourceClause: "8类问题之二：软色情擦边",
    originalText: "聚焦软色情擦边等8类问题",
    sourceConfidence: "official_text",
    scope: ["full_text"],
    keywords: ["夜总会陪酒", "按摩女", "会所小姐", "女主播打赏"],
    patterns: [],
    cooccurrence: [
      { groupA: ["女主播", "网红"], groupB: ["榜一大哥", "线下见面", "打赏"], window: 80 },
    ],
    baseConfidence: "0.72",
    remediationTemplate:
      "命中擦边场景设定提示（依据：专项治理8类问题之二）。该类设定本身不必然违规，但若与性暗示描写叠加将升级为高危，建议自查上下文并做中性化处理。",
    platformOverrides: {},
  },
  // ============ 3. 拜金炫富 ============
  {
    ruleCode: "R3-2026-001",
    version: "1.0.0",
    category: "money_worship",
    name: "炫耀性消费与拜金价值观",
    severity: "high",
    sourcePolicy: POLICY_202606,
    sourceClause: "8类问题之三：拜金炫富",
    originalText: "聚焦拜金炫富等8类问题",
    sourceConfidence: "official_text",
    scope: ["dialogue", "narration", "full_text"],
    keywords: ["炫富", "拜金", "嫁入豪门", "傍大款", "一掷千金"],
    patterns: [
      "(劳斯莱斯|法拉利|兰博基尼|宾利|保时捷).{0,10}(车队|一排|十辆|百辆)",
      "(现金|钞票).{0,6}(砸|甩|摔).{0,6}(脸|地上)",
      "(一亿|十亿|百亿).{0,8}(零花钱|分手费|彩礼)",
    ],
    cooccurrence: [
      { groupA: ["穷", "没钱", "穷人"], groupB: ["不配", "滚", "废物", "贱"], window: 40 },
    ],
    baseConfidence: "0.80",
    remediationTemplate:
      "命中拜金炫富判定（依据：专项治理8类问题之三）。建议弱化财富数字堆砌与以财压人情节，冲突动机改为能力/情感驱动；避免将财富与尊严直接挂钩的台词。",
    platformOverrides: {},
  },
  // ============ 4. 畸形婚恋观 ============
  {
    ruleCode: "R4-2026-001",
    version: "1.0.0",
    category: "marriage_distortion",
    name: "出轨美化/婚外情正当化",
    severity: "high",
    sourcePolicy: POLICY_202606,
    sourceClause: "8类问题之四：畸形婚恋观",
    originalText: "聚焦畸形婚恋观等8类问题",
    sourceConfidence: "official_text",
    scope: ["full_text"],
    keywords: ["小三上位", "出轨有理", "婚外情", "正室大战小三"],
    patterns: ["(出轨|偷情|劈腿).{0,12}(真爱|追求幸福|无可厚非)"],
    cooccurrence: [
      { groupA: ["小三", "情人"], groupB: ["转正", "上位", "胜利"], window: 60 },
    ],
    baseConfidence: "0.78",
    remediationTemplate:
      "命中畸形婚恋观判定（依据：专项治理8类问题之四）。婚外情题材本身可创作，但不得美化出轨方或宣扬'出轨即真爱'的价值观，建议调整叙事立场并增加对婚姻责任的正面表达。",
    platformOverrides: {},
  },
  {
    ruleCode: "R4-2026-002",
    version: "1.0.0",
    category: "marriage_distortion",
    name: "闪婚闪育/代孕情节",
    severity: "notice",
    sourcePolicy: POLICY_202606,
    sourceClause: "8类问题之四：畸形婚恋观",
    originalText: "聚焦畸形婚恋观等8类问题",
    sourceConfidence: "official_text",
    scope: ["full_text"],
    keywords: ["代孕", "借腹生子", "买精生子", "契约婚姻"],
    patterns: ["(代孕|借腹).{0,10}(协议|合同|交易|费用)"],
    cooccurrence: [],
    baseConfidence: "0.80",
    remediationTemplate:
      "命中代孕/契约生育情节（依据：专项治理8类问题之四）。代孕在我国属禁止性行为，剧本不得将其正当化或作为正面情节推进手段，建议替换为领养或其他合法设定。",
    platformOverrides: { hongguo: { severity: "high" } },
  },
  // ============ 5. 封建糟粕 ============
  {
    ruleCode: "R5-2026-001",
    version: "1.0.0",
    category: "feudal_dregs",
    name: "宣扬迷信与封建糟粕",
    severity: "high",
    sourcePolicy: POLICY_202606,
    sourceClause: "8类问题之五：封建糟粕",
    originalText: "聚焦封建糟粕等8类问题",
    sourceConfidence: "official_text",
    scope: ["full_text"],
    keywords: ["转世投胎", "厉鬼索命", "风水改运", "算命改命", "冲喜", "冥婚", "配阴婚"],
    patterns: ["(冥婚|阴婚|冲喜).{0,15}(仪式|拜堂|成亲)"],
    cooccurrence: [
      { groupA: ["大师", "道长", "神婆"], groupB: ["作法", "改命", "消灾", "灵验"], window: 60 },
    ],
    baseConfidence: "0.78",
    remediationTemplate:
      "命中封建糟粕判定（依据：专项治理8类问题之五）。民俗元素可作为背景，但不得宣扬迷信有效性（作法消灾、冥婚仪式等），建议改为悬疑/心理向解释或明确批判立场。",
    platformOverrides: {},
  },
  // ============ 6. 暴力复仇 ============
  {
    ruleCode: "R6-2026-001",
    version: "1.0.0",
    category: "violent_revenge",
    name: "以暴制暴与私刑复仇",
    severity: "high",
    sourcePolicy: POLICY_202606,
    sourceClause: "8类问题之六：暴力复仇",
    originalText: "聚焦暴力复仇等8类问题",
    sourceConfidence: "official_text",
    scope: ["full_text"],
    keywords: ["灭门", "血债血偿", "以牙还牙", "私刑", "活埋", "沉塘"],
    patterns: [
      "(杀|弄死|做掉|废了他).{0,8}(全家|满门|仇人)",
      "(复仇|报仇).{0,15}(杀人|下毒|纵火|绑架)",
    ],
    cooccurrence: [
      { groupA: ["复仇", "报仇"], groupB: ["爽快", "解气", "大快人心"], window: 60 },
    ],
    baseConfidence: "0.78",
    remediationTemplate:
      "命中暴力复仇判定（依据：专项治理8类问题之六）。复仇主线可保留，但结局须回归法治框架（报警、诉讼、舆论监督），不得将私刑呈现为正义实现方式并渲染其快感。",
    platformOverrides: {},
  },
  {
    ruleCode: "R6-2026-002",
    version: "1.0.0",
    category: "violent_revenge",
    name: "暴力细节渲染",
    severity: "notice",
    sourcePolicy: POLICY_202606,
    sourceClause: "8类问题之六：暴力复仇",
    originalText: "聚焦暴力复仇等8类问题",
    sourceConfidence: "official_text",
    scope: ["full_text"],
    keywords: ["剁手", "挖眼", "打断腿", "挑断手筋"],
    patterns: ["(刀|棍|铁链).{0,10}(打断|砍|抽).{0,8}(骨|筋|腿|手)"],
    cooccurrence: [],
    baseConfidence: "0.75",
    remediationTemplate:
      "命中暴力细节渲染提示（依据：专项治理8类问题之六）。建议删除具体伤残手段的细节描写，暴力场面以结果呈现替代过程渲染。",
    platformOverrides: {},
  },
  // ============ 7. 低俗片名（阻断级） ============
  {
    ruleCode: "R7-2026-001",
    version: "1.0.0",
    category: "vulgar_title",
    name: "低俗暗示片名",
    severity: "block",
    sourcePolicy: POLICY_202606,
    sourceClause: "8类问题之七：低俗片名",
    originalText: "聚焦低俗片名等8类问题",
    sourceConfidence: "official_text",
    scope: ["title", "episode_title", "promo_copy"],
    keywords: ["床上", "风骚", "欲女", "淫", "娇喘", "春色"],
    patterns: ["(小娇妻|小逃妻|尤物)", "(风骚|欲女|娇喘)"],
    cooccurrence: [],
    baseConfidence: "0.88",
    remediationTemplate:
      "片名[{span}]命中低俗暗示判定（依据：专项治理8类问题之七）。建议替换为中性情节描述型片名，避免身体部位/性暗示/猎奇措辞。",
    platformOverrides: { hongguo: { severity: "block", note: "平台片名审核口径更严" } },
  },
  {
    ruleCode: "R7-2026-002",
    version: "1.0.0",
    category: "vulgar_title",
    name: "猎奇擦边片名",
    severity: "high",
    sourcePolicy: POLICY_202606,
    sourceClause: "8类问题之七：低俗片名",
    originalText: "聚焦低俗片名等8类问题",
    sourceConfidence: "official_text",
    scope: ["title", "episode_title", "promo_copy"],
    keywords: ["赘婿的床", "风流", "桃色", "偷情", "欲望"],
    patterns: [],
    cooccurrence: [],
    baseConfidence: "0.78",
    remediationTemplate:
      "片名[{span}]命中猎奇擦边判定（依据：专项治理8类问题之七）。建议避免以情色联想为卖点的命名，改用人物目标或核心冲突命名。",
    platformOverrides: {},
  },
  // ============ 8. 侵权盗版 ============
  {
    ruleCode: "R8-2026-001",
    version: "1.0.0",
    category: "ip_infringement",
    name: "未授权改编与洗稿风险",
    severity: "high",
    sourcePolicy: POLICY_202606,
    sourceClause: "8类问题之八：侵权盗版",
    originalText: "聚焦侵权盗版等8类问题",
    sourceConfidence: "official_text",
    scope: ["full_text"],
    keywords: ["改编自", "同人", "致敬经典"],
    patterns: ["改编自《[^》]+》(?!（已获授权）)"],
    cooccurrence: [],
    baseConfidence: "0.70",
    remediationTemplate:
      "命中改编声明（依据：专项治理8类问题之八）。请确认已取得原IP改编授权并完成授权链留痕（授权申请→改编红线→关键剧情确认→成片备案六节点）；无授权改编2025年多起判例索赔超20万元。",
    platformOverrides: {},
  },
  {
    ruleCode: "R8-2026-002",
    version: "2.0.0",
    category: "ip_infringement",
    name: "经典IP形象出现提示",
    severity: "notice",
    sourcePolicy: POLICY_202412,
    sourceClause: "AI魔改经典作品管理提示",
    originalText: "毫无边界亵渎经典IP、篡改经典人物形象属重点治理对象",
    sourceConfidence: "official_text",
    scope: ["full_text"],
    keywords: [
      "奥特曼", "孙悟空", "林黛玉", "诸葛亮", "白蛇", "白娘子", "葫芦娃", "黑猫警长",
      "哪吒", "姜子牙", "貂蝉", "武松", "潘金莲", "嫦娥", "花木兰", "甄嬛", "花千骨",
      "哆啦A梦", "柯南", "路飞", "鸣人", "叶问", "黄飞鸿", "东方不败", "令狐冲",
      "郭靖", "黄蓉", "杨过", "小龙女", "乔峰", "韦小宝", "张无忌", "李逍遥",
    ],
    patterns: [],
    cooccurrence: [],
    baseConfidence: "0.60",
    remediationTemplate:
      "检测到经典IP形象[{span}]出现（依据：2024年12月《管理提示（AI魔改）》）。IP出现本身不构成违规，但请确认：①已取得改编授权；②授权链六节点留痕完整；③改编幅度未触碰亵渎红线（系统已对犯罪/色情/恶搞/言情化偏离做共现检测，见高危/阻断级命中）。",
    platformOverrides: {},
  },
  // ============ 备案/标识形式要件（元数据类） ============
  {
    ruleCode: "R9-2026-001",
    version: "1.0.0",
    category: "ip_infringement",
    name: "备案号与AI标识形式要件提示",
    severity: "notice",
    sourcePolicy: POLICY_202604,
    sourceClause: "备案强制化与AI标识要求",
    originalText: "2026年4月1日起未备案作品全网强制下架，平台不得上线无备案号作品；每集明显位置须添加AI标识",
    sourceConfidence: "official_text",
    scope: ["full_text"],
    keywords: [],
    patterns: [],
    cooccurrence: [],
    baseConfidence: "0.99",
    remediationTemplate:
      "形式要件提示：请确认①已完成备案并取得备案号；②每集明显位置已嵌入AI标识且位置/字体/时长符合平台口径；③分层口径：真人剧 2026-01-01 起施行新标准（重点≥300万/普通100–300万）；AI剧适用独立更严口径（重点≥80万/普通30–80万，企服解读，以广电原文为准）。",
    platformOverrides: {},
  },
];

